[build-system]
requires = ["setuptools>=68.2.2"]
build-backend = "setuptools.build_meta"

[project]
name = "pmodels"
version = "0.0.0"
requires-python = ">=3.11.5"

dependencies = [
    "pandas==2.1.1",
]
